/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RiskScoreDistributionListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheRiskScoreDistributionList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheRiskScoreDistributionList.onFilterBar().iCheckFilterField("Year");
            Then.onTheRiskScoreDistributionList.onFilterBar().iCheckFilterField("State");
            Then.onTheRiskScoreDistributionList.onFilterBar().iCheckFilterField("ProviderType");
            Then.onTheRiskScoreDistributionList.onFilterBar().iCheckFilterField("RiskBand");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheRiskScoreDistributionList.onTable().iCheckColumns(undefined, {"Year":{"header":"Year"},"State":{"header":"State"},"ProviderType":{"header":"Provider Type"},"RiskBand":{"header":"Risk Band"},"ProviderCount":{"header":"Provider Count"},"TotalBeneficiaries":{"header":"Total Beneficiaries"},"AvgRiskScore":{"header":"Avg Risk Score"},"AvgHypertensionPct":{"header":"Avg Hypertension %"},"AvgDiabetesPct":{"header":"Avg Diabetes %"},"TotalPaid":{"header":"Total Paid ($)"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheRiskScoreDistributionList.onFilterBar().iExecuteSearch();
            
            Then.onTheRiskScoreDistributionList.onTable().iCheckRows();

            When.onTheRiskScoreDistributionList.onTable().iPressRow(0);
            Then.onTheRiskScoreDistributionObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});