/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("RuralUrbanDistributionListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheRuralUrbanDistributionList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheRuralUrbanDistributionList.onFilterBar().iCheckFilterField("Year");
            Then.onTheRuralUrbanDistributionList.onFilterBar().iCheckFilterField("State");
            Then.onTheRuralUrbanDistributionList.onFilterBar().iCheckFilterField("RuralUrban");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheRuralUrbanDistributionList.onTable().iCheckColumns(undefined, {"Year":{"header":"Year"},"State":{"header":"State"},"RuralUrban":{"header":"Rural/Urban"},"ProviderCount":{"header":"Provider Count"},"TotalSubmitted":{"header":"Total Submitted ($)"},"TotalAllowed":{"header":"Total Allowed ($)"},"TotalPaid":{"header":"Total Paid ($)"},"TotalBeneficiaries":{"header":"Total Beneficiaries"},"AvgRiskScore":{"header":"Avg Risk Score"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheRuralUrbanDistributionList.onFilterBar().iExecuteSearch();
            
            Then.onTheRuralUrbanDistributionList.onTable().iCheckRows();

            When.onTheRuralUrbanDistributionList.onTable().iPressRow(0);
            Then.onTheRuralUrbanDistributionObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});