/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BehavioralHealthRiskProfileListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheBehavioralHealthRiskProfileListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheBehavioralHealthRiskProfileListGenerated.onFilterBar().iCheckFilterField("State");
            Then.onTheBehavioralHealthRiskProfileListGenerated.onFilterBar().iCheckFilterField("ProviderType");
            Then.onTheBehavioralHealthRiskProfileListGenerated.onFilterBar().iCheckFilterField("BHBurdenGroup");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheBehavioralHealthRiskProfileListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheBehavioralHealthRiskProfileListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheBehavioralHealthRiskProfileListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheBehavioralHealthRiskProfileListGenerated.onTable().iCheckColumns(undefined, {"State":{"header":"State"},"ProviderType":{"header":"ProviderType"},"BHBurdenGroup":{"header":"BHBurdenGroup"},"ProviderCount":{"header":"ProviderCount"},"AvgRiskScore":{"header":"AvgRiskScore"},"PaidPerBeneficiary":{"header":"PaidPerBeneficiary"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheBehavioralHealthRiskProfileListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheBehavioralHealthRiskProfileListGenerated.onTable().iCheckRows();

            When.onTheBehavioralHealthRiskProfileListGenerated.onTable().iPressRow(0);
            Then.onTheBehavioralHealthRiskProfileObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});