/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ProviderCostEfficiencyListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheProviderCostEfficiencyList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheProviderCostEfficiencyList.onFilterBar().iCheckFilterField("Year");
            Then.onTheProviderCostEfficiencyList.onFilterBar().iCheckFilterField("State");
            Then.onTheProviderCostEfficiencyList.onFilterBar().iCheckFilterField("ProviderType");
            Then.onTheProviderCostEfficiencyList.onFilterBar().iCheckFilterField("RiskCategory");
            Then.onTheProviderCostEfficiencyList.onFilterBar().iCheckFilterField("EfficiencyCategory");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheProviderCostEfficiencyList.onTable().iCheckColumns(undefined, {"Year":{"header":"Year"},"ProviderName":{"header":"Provider Name"},"ProviderType":{"header":"Specialty"},"State":{"header":"State"},"City":{"header":"City"},"TotalBeneficiaries":{"header":"Beneficiaries"},"CostPerBeneficiary":{"header":"Cost Per Beneficiary ($)"},"TotalPaid":{"header":"Total Paid ($)"},"EfficiencyCategory":{"header":"Efficiency"},"RiskCategory":{"header":"Risk Profile"},"UtilizationCategory":{"header":"Utilization"},"AvgRiskScore":{"header":"Avg Risk Score"},"DiabetesPct":{"header":"Diabetes %"},"HypertensionPct":{"header":"Hypertension %"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheProviderCostEfficiencyList.onFilterBar().iExecuteSearch();
            
            Then.onTheProviderCostEfficiencyList.onTable().iCheckRows();

            When.onTheProviderCostEfficiencyList.onTable().iPressRow(0);
            Then.onTheProviderCostEfficiencyObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});