/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CostByStateProviderTypeListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheCostByStateProviderTypeList.iSeeThisPage();
        });


        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheCostByStateProviderTypeList.onTable().iCheckColumns(undefined, {"Year":{"header":"Year"},"State":{"header":"State"},"ProviderType":{"header":"ProviderType"},"ProviderCount":{"header":"ProviderCount"},"TotalSubmitted":{"header":"TotalSubmitted"},"TotalAllowed":{"header":"TotalAllowed"},"TotalPaid":{"header":"TotalPaid"},"TotalBeneficiaries":{"header":"TotalBeneficiaries"},"AvgRiskScore":{"header":"AvgRiskScore"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheCostByStateProviderTypeList.onFilterBar().iExecuteSearch();
            
            Then.onTheCostByStateProviderTypeList.onTable().iCheckRows();

            When.onTheCostByStateProviderTypeList.onTable().iPressRow(0);
            Then.onTheCostByStateProviderTypeObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});