/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ProviderAnalyticsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheProviderAnalyticsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheProviderAnalyticsList.onFilterBar().iCheckFilterField("Year");
            Then.onTheProviderAnalyticsList.onFilterBar().iCheckFilterField("State");
            Then.onTheProviderAnalyticsList.onFilterBar().iCheckFilterField("Provider Type");
            Then.onTheProviderAnalyticsList.onFilterBar().iCheckFilterField("Area (Rural/Urban)");
            Then.onTheProviderAnalyticsList.onFilterBar().iCheckFilterField("Risk Band");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheProviderAnalyticsList.onTable().iCheckColumns(undefined, {"Year":{"header":"Year"},"State":{"header":"State"},"ProviderType":{"header":"Provider Type"},"AreaType":{"header":"Area (Rural/Urban)"},"RiskBand":{"header":"Risk Band"},"PaidAmount":{"header":"Paid Amount"},"SubmittedCharges":{"header":"Submitted Charges"},"AllowedAmount":{"header":"Allowed Amount"},"Beneficiaries":{"header":"Beneficiaries"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheProviderAnalyticsList.onFilterBar().iExecuteSearch();
            
            Then.onTheProviderAnalyticsList.onTable().iCheckRows();

            When.onTheProviderAnalyticsList.onTable().iPressRow(0);
            Then.onTheProviderAnalyticsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});